spring:
  datasource:
    password: POLL
    url: jdbc:oracle:thin:@localhost:1521:orcl1
    username: POLL
logging:
  level:
    web: debug
    sql: debug

allow-origin:
  address: http://localhost
  port: 8080
